# Generated by Django 5.0 on 2023-12-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_rename_title_post_title1_remove_post_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminBlogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=240, null=True)),
            ],
        ),
    ]
