# Generated by Django 5.0 on 2023-12-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_adminblogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminblogs',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='adminblogs',
            name='date',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
